export const games = [
  {
    id: 1,
    title: "Doom Eternal",
    price: 29.99,
    type: "Action",
    image: "/images/doometernal.png",
    inCart: false,
  },
  {
    id: 2,
    title: "Call of Duty: Modern Warfare",
    price: 59.99,
    type: "Action",
    image: "/images/CODMW.webp",
    inCart: false,
  },
  {
    id: 3,
    title: "Devil May Cry 5",
    price: 39.99,
    type: "Action",
    image: "/images/DMC5.webp",
    inCart: false,
  },
  {
    id: 4,
    title: "God of War: Ragnarok",
    price: 49.99,
    type: "Action",
    image: "/images/GOWR.webp",
    inCart: false,
  },
  {
    id: 5,
    title: "Bayonetta 2",
    price: 34.99,
    type: "Action",
    image: "/images/Bayonetta2.webp",
    inCart: false,
  },

  {
    id: 6,
    title: "The Legend of Zelda: Breath of the Wild",
    price: 59.99,
    type: "Adventure",
    image: "/",
    inCart: false,
  },
  {
    id: 7,
    title: "Uncharted 4: A Thief's End",
    price: 39.99,
    type: "Adventure",
    image: "/",
    inCart: false,
  },
  {
    id: 8,
    title: "Tomb Raider",
    price: 29.99,
    type: "Adventure",
    image: "/",
    inCart: false,
  },
  {
    id: 9,
    title: "Assassin's Creed Odyssey",
    price: 49.99,
    type: "Adventure",
    image: "/",
    inCart: false,
  },
  {
    id: 10,
    title: "Red Dead Redemption 2",
    price: 59.99,
    type: "Adventure",
    image: "/",
    inCart: false,
  },

  {
    id: 11,
    title: "The Sims 4",
    price: 39.99,
    type: "Simulation",
    image: "/",
    inCart: false,
  },
  {
    id: 12,
    title: "Stardew Valley",
    price: 14.99,
    type: "Simulation",
    image: "/",
    inCart: false,
  },
  {
    id: 13,
    title: "Cities: Skylines",
    price: 29.99,
    type: "Simulation",
    image: "/",
    inCart: false,
  },
  {
    id: 14,
    title: "Planet Zoo",
    price: 49.99,
    type: "Simulation",
    image: "/",
    inCart: false,
  },
  {
    id: 15,
    title: "Euro Truck Simulator 2",
    price: 19.99,
    type: "Simulation",
    image: "/",
    inCart: false,
  },


  {
    id: 16,
    title: "Resident Evil Village",
    price: 59.99,
    type: "Horror",
    image: "/",
    inCart: false,
  },
  {
    id: 17,
    title: "Outlast 2",
    price: 19.99,
    type: "Horror",
    image: "/",
    inCart: false,
  },
  {
    id: 18,
    title: "Silent Hill 2",
    price: 24.99,
    type: "Horror",
    image: "/",
    inCart: false,
  },
  {
    id: 19,
    title: "Amnesia: The Dark Descent",
    price: 14.99,
    type: "Horror",
    image: "/",
    inCart: false,
  },
  {
    id: 20,
    title: "Fatal Frame II",
    price: 29.99,
    type: "Horror",
    image: "/",
    inCart: false,
  },

  {
    id: 21,
    title: "Final Fantasy VII Remake",
    price: 59.99,
    type: "RPG",
    image: "/",
    inCart: false,
  },
  {
    id: 22,
    title: "The Witcher 3: Wild Hunt",
    price: 39.99,
    type: "RPG",
    image: "/",
    inCart: false,
  },
  {
    id: 23,
    title: "Skyrim",
    price: 29.99,
    type: "RPG",
    image: "/",
    inCart: false,
  },
  {
    id: 24,
    title: "Dragon Age: Inquisition",
    price: 34.99,
    type: "RPG",
    image: "/",
    inCart: false,
  },
  {
    id: 25,
    title: "Persona 5",
    price: 49.99,
    type: "RPG",
    image: "/",
    inCart: false,
  }
];
